export default [
	{
		country: 'Afghanistan',
		currency_code: 'AFN',
		call_code: '+93',
		capital: 'Kabul',
	},
	{
		country: 'Aland Islands',
		currency_code: 'EUR',
		call_code: '+358',
		capital: 'Mariehamn',
	},
	{
		country: 'Albania',
		currency_code: 'ALL',
		call_code: '+355',
		capital: 'Tirana',
	},
	{
		country: 'Algeria',
		currency_code: 'DZD',
		call_code: '+213',
		capital: 'Algiers',
	},
	{
		country: 'American Samoa',
		currency_code: 'USD',
		call_code: '+1684',
		capital: 'Pago Pago',
	},
	{
		country: 'Andorra',
		currency_code: 'EUR',
		call_code: '+376',
		capital: 'Andorra la Vella',
	},
	{
		country: 'Angola',
		currency_code: 'AOA',
		call_code: '+244',
		capital: 'Luanda',
	},
	{
		country: 'Anguilla',
		currency_code: 'XCD',
		call_code: '+1264',
		capital: 'The Valley',
	},
	{
		country: 'Antarctica',
		currency_code: 'XCD',
		call_code: '+672',
		capital: '',
	},
	{
		country: 'Antigua and Barbuda',
		currency_code: 'ECD',
		call_code: '+1268',
		capital: 'Saint John\'s',
	},
	{
		country: 'Argentina',
		currency_code: 'ARS',
		call_code: '+54',
		capital: 'Buenos Aires',
	},
	{
		country: 'Armenia',
		currency_code: 'AMD',
		call_code: '+374',
		capital: 'Yerevan',
	},
	{
		country: 'Aruba',
		currency_code: 'AWG',
		call_code: '+297',
		capital: 'Oranjestad',
	},
	{
		country: 'Australia',
		currency_code: 'AUD',
		call_code: '+61',
		capital: 'Canberra',
	},
	{
		country: 'Austria',
		currency_code: 'EUR',
		call_code: '+43',
		capital: 'Vienna',
	},
	{
		country: 'Azerbaijan',
		currency_code: 'AZN',
		call_code: '+994',
		capital: 'Baku',
	},
	{
		country: 'Bahamas',
		currency_code: 'BSD',
		call_code: '+1242',
		capital: 'Nassau',
	},
	{
		country: 'Bahrain',
		currency_code: 'BHD',
		call_code: '+973',
		capital: 'Manama',
	},
	{
		country: 'Bangladesh',
		currency_code: 'BDT',
		call_code: '+880',
		capital: 'Dhaka',
	},
	{
		country: 'Barbados',
		currency_code: 'BBD',
		call_code: '+1246',
		capital: 'Bridgetown',
	},
	{
		country: 'Belarus',
		currency_code: 'BYR',
		call_code: '+375',
		capital: 'Minsk',
	},
	{
		country: 'Belgium',
		currency_code: 'EUR',
		call_code: '+32',
		capital: 'Brussels',
	},
	{
		country: 'Belize',
		currency_code: 'BZD',
		call_code: '+501',
		capital: 'Belmopan',
	},
	{
		country: 'Benin',
		currency_code: 'XOF',
		call_code: '+229',
		capital: 'Porto-Novo',
	},
	{
		country: 'Bermuda',
		currency_code: 'BMD',
		call_code: '+1441',
		capital: 'Hamilton',
	},
	{
		country: 'Bhutan',
		currency_code: 'BTN',
		call_code: '+975',
		capital: 'Thimphu',
	},
	{
		country: 'Bolivia',
		currency_code: 'BOB',
		call_code: '+591',
		capital: 'La Paz',
	},
	{
		country: 'Bosnia and Herzegovina',
		currency_code: 'BAM',
		call_code: '+387',
		capital: 'Sarajevo',
	},
	{
		country: 'Botswana',
		currency_code: 'BWP',
		call_code: '+267',
		capital: 'Gaborone',
	},
	{
		country: 'Bouvet Island',
		currency_code: 'NOK',
		call_code: '+47',
		capital: '',
	},
	{
		country: 'Brazil',
		currency_code: 'BRL',
		call_code: '+55',
		capital: 'Brasilia',
	},
	{
		country: 'British Indian Ocean Territory',
		currency_code: 'USD',
		call_code: '+246',
		capital: '',
	},
	{
		country: 'Brunei',
		currency_code: 'BND',
		call_code: '+673',
		capital: 'Bandar Seri Begawan',
	},
	{
		country: 'Bulgaria',
		currency_code: 'BGN',
		call_code: '+359',
		capital: 'Sofia',
	},
	{
		country: 'Burkina Faso',
		currency_code: 'XOF',
		call_code: '+226',
		capital: 'Ouagadougou',
	},
	{
		country: 'Burundi',
		currency_code: 'BIF',
		call_code: '+257',
		capital: 'Bujumbura',
	},
	{
		country: 'Cambodia',
		currency_code: 'KHR',
		call_code: '+855',
		capital: 'Phnom Penh',
	},
	{
		country: 'Cameroon',
		currency_code: 'XAF',
		call_code: '+237',
		capital: 'Yaounde',
	},
	{
		country: 'Canada',
		currency_code: 'CAD',
		call_code: '+1',
		capital: 'Ottawa',
	},
	{
		country: 'Cape Verde',
		currency_code: 'CVE',
		call_code: '+238',
		capital: 'Praia',
	},
	{
		country: 'Cayman Islands',
		currency_code: 'KYD',
		call_code: '+1345',
		capital: 'George Town',
	},
	{
		country: 'Central African Republic',
		currency_code: 'XAF',
		call_code: '+236',
		capital: 'Bangui',
	},
	{
		country: 'Chad',
		currency_code: 'XAF',
		call_code: '+235',
		capital: 'N\'Djamena',
	},
	{
		country: 'Chile',
		currency_code: 'CLP',
		call_code: '+56',
		capital: 'Santiago',
	},
	{
		country: 'China',
		currency_code: 'CNY',
		call_code: '+86',
		capital: 'Beijing',
	},
	{
		country: 'Christmas Island',
		currency_code: 'AUD',
		call_code: '+61',
		capital: '',
	},
	{
		country: 'Cocos (Keeling) Islands',
		currency_code: 'AUD',
		call_code: '+61',
		capital: '',
	},
	{
		country: 'Colombia',
		currency_code: 'COP',
		call_code: '+57',
		capital: 'Bogota',
	},
	{
		country: 'Comoros',
		currency_code: 'KMF',
		call_code: '+269',
		capital: 'Moroni',
	},
	{
		country: 'Congo',
		currency_code: 'XAF',
		call_code: '+242',
		capital: 'Brazzaville',
	},
	{
		country: 'Cook Islands',
		currency_code: 'NZD',
		call_code: '+682',
		capital: '',
	},
	{
		country: 'Costa Rica',
		currency_code: 'CRC',
		call_code: '+506',
		capital: 'San Jose',
	},
	{
		country: 'Croatia',
		currency_code: 'HRK',
		call_code: '+385',
		capital: 'Zagreb',
	},
	{
		country: 'Cuba',
		currency_code: 'CUP',
		call_code: '+53',
		capital: 'Havana',
	},
	{
		country: 'Cyprus',
		currency_code: 'EUR',
		call_code: '+357',
		capital: 'Nicosia',
	},
	{
		country: 'Czech Republic',
		currency_code: 'CZK',
		call_code: '+420',
		capital: 'Prague',
	},
	{
		country: 'Denmark',
		currency_code: 'DKK',
		call_code: '+45',
		capital: 'Copenhagen',
	},
	{
		country: 'Djibouti',
		currency_code: 'DJF',
		call_code: '+253',
		capital: 'Djibouti',
	},
	{
		country: 'Dominica',
		currency_code: 'XCD',
		call_code: '+1767',
		capital: 'Roseau',
	},
	{
		country: 'Dominican Republic',
		currency_code: 'DOP',
		call_code: '+1809',
		capital: 'Santo Domingo',
	},
	{
		country: 'East Timor',
		currency_code: 'USD',
		call_code: '+670',
		capital: 'Dili',
	},
	{
		country: 'Ecuador',
		currency_code: 'ECS',
		call_code: '+593',
		capital: 'Quito',
	},
	{
		country: 'Egypt',
		currency_code: 'EGP',
		call_code: '+20',
		capital: 'Cairo',
	},
	{
		country: 'El Salvador',
		currency_code: 'SVC',
		call_code: '+503',
		capital: 'San Salvador',
	},
	{
		country: 'England',
		currency_code: 'GBP',
		call_code: '+44',
		capital: 'London',
	},
	{
		country: 'Equatorial Guinea',
		currency_code: 'XAF',
		call_code: '+240',
		capital: 'Malabo',
	},
	{
		country: 'Eritrea',
		currency_code: 'ERN',
		call_code: '+291',
		capital: 'Asmara',
	},
	{
		country: 'Estonia',
		currency_code: 'EUR',
		call_code: '+372',
		capital: 'Tallinn',
	},
	{
		country: 'Ethiopia',
		currency_code: 'ETB',
		call_code: '+251',
		capital: 'Addis Ababa',
	},
	{
		country: 'Falkland Islands',
		currency_code: 'FKP',
		call_code: '+500',
		capital: 'Stanley',
	},
	{
		country: 'Faroe Islands',
		currency_code: 'DKK',
		call_code: '+298',
		capital: 'Torshavn',
	},
	{
		country: 'Fiji Islands',
		currency_code: 'FJD',
		call_code: '+679',
		capital: 'Suva',
	},
	{
		country: 'Finland',
		currency_code: 'EUR',
		call_code: '+358',
		capital: 'Helsinki',
	},
	{
		country: 'France',
		currency_code: 'EUR',
		call_code: '+33',
		capital: 'Paris',
	},
	{
		country: 'French Guiana',
		currency_code: 'EUR',
		call_code: '+594',
		capital: 'Cayenne',
	},
	{
		country: 'French Polynesia',
		currency_code: 'XPF',
		call_code: '+689',
		capital: 'Papeete',
	},
	{
		country: 'French Southern territories',
		currency_code: 'EUR',
		call_code: '+262',
		capital: '',
	},
	{
		country: 'Gabon',
		currency_code: 'XAF',
		call_code: '+241',
		capital: 'Libreville',
	},
	{
		country: 'Gambia',
		currency_code: 'GMD',
		call_code: '+220',
		capital: 'Banjul',
	},
	{
		country: 'Georgia',
		currency_code: 'GEL',
		call_code: '+995',
		capital: 'Tbilisi',
	},
	{
		country: 'Germany',
		currency_code: 'EUR',
		call_code: '+49',
		capital: 'Berlin',
	},
	{
		country: 'Ghana',
		currency_code: 'GHS',
		call_code: '+233',
		capital: 'Accra',
	},
	{
		country: 'Gibraltar',
		currency_code: 'GIP',
		call_code: '+350',
		capital: 'Gibraltar',
	},
	{
		country: 'Greece',
		currency_code: 'EUR',
		call_code: '+30',
		capital: 'Athens',
	},
	{
		country: 'Greenland',
		currency_code: 'DKK',
		call_code: '+299',
		capital: 'Nuuk',
	},
	{
		country: 'Grenada',
		currency_code: 'XCD',
		call_code: '+1473',
		capital: 'St. George\'s',
	},
	{
		country: 'Guadeloupe',
		currency_code: 'EUR',
		call_code: '+590',
		capital: 'Basse-Terre',
	},
	{
		country: 'Guam',
		currency_code: 'USD',
		call_code: '+1671',
		capital: 'Hagatna',
	},
	{
		country: 'Guatemala',
		currency_code: 'QTQ',
		call_code: '+502',
		capital: 'Guatemala City',
	},
	{
		country: 'Guinea',
		currency_code: 'GNF',
		call_code: '+224',
		capital: 'Conakry',
	},
	{
		country: 'Guinea-Bissau',
		currency_code: 'CFA',
		call_code: '+245',
		capital: 'Bissau',
	},
	{
		country: 'Guyana',
		currency_code: 'GYD',
		call_code: '+592',
		capital: 'Georgetown',
	},
	{
		country: 'Haiti',
		currency_code: 'HTG',
		call_code: '+509',
		capital: 'Port-au-Prince',
	},
	{
		country: 'Heard Island and McDonald Islands',
		currency_code: 'AUD',
		call_code: '+672',
		capital: '',
	},
	{
		country: 'Holy See (Vatican City State)',
		currency_code: 'EUR',
		call_code: '+379',
		capital: 'Vatican City',
	},
	{
		country: 'Honduras',
		currency_code: 'HNL',
		call_code: '+504',
		capital: 'Tegucigalpa',
	},
	{
		country: 'Hong Kong',
		currency_code: 'HKD',
		call_code: '+852',
		capital: 'Hong Kong',
	},
	{
		country: 'Hungary',
		currency_code: 'HUF',
		call_code: '+36',
		capital: 'Budapest',
	},
	{
		country: 'Iceland',
		currency_code: 'ISK',
		call_code: '+354',
		capital: 'Reykjavik',
	},
	{
		country: 'India',
		currency_code: 'INR',
		call_code: '+91',
		capital: 'New Delhi',
	},
	{
		country: 'Indonesia',
		currency_code: 'IDR',
		call_code: '+62',
		capital: 'Jakarta',
	},
	{
		country: 'Iran',
		currency_code: 'IRR',
		call_code: '+98',
		capital: 'Tehran',
	},
	{
		country: 'Iraq',
		currency_code: 'IQD',
		call_code: '+964',
		capital: 'Baghdad',
	},
	{
		country: 'Ireland',
		currency_code: 'EUR',
		call_code: '+353',
		capital: 'Dublin',
	},
	{
		country: 'Israel',
		currency_code: 'ILS',
		call_code: '+972',
		capital: 'Jerusalem',	
	},
	{
		country: 'Italy',
		currency_code: 'EUR',
		call_code: '+39',
		capital: 'Rome',
	},
	{
		country: 'Ivory Coast',
		currency_code: 'XOF',
		call_code: '+225',
		capital: 'Yamoussoukro',
	},
	{
		country: 'Jamaica',
		currency_code: 'JMD',
		call_code: '+1876',
		capital: 'Kingston',
	},
	{
		country: 'Japan',
		currency_code: 'JPY',
		call_code: '+81',
		capital: 'Tokyo',
	},
	{
		country: 'Jordan',
		currency_code: 'JOD',
		call_code: '+962',
		capital: 'Amman',
	},
	{
		country: 'Kazakhstan',
		currency_code: 'KZT',
		call_code: '+7',
		capital: 'Astana',
	},
	{
		country: 'Kenya',
		currency_code: 'KES',
		call_code: '+254',
		capital: 'Nairobi',
	},
	{
		country: 'Kiribati',
		currency_code: 'AUD',
		call_code: '+686',
		capital: 'South Tarawa',
	},
	{
		country: 'Kuwait',
		currency_code: 'KWD',
		call_code: '+965',
		capital: 'Kuwait City',
	},
	{
		country: 'Kyrgyzstan',
		currency_code: 'KGS',
		call_code: '+996',
		capital: 'Bishkek',
	},
	{
		country: 'Laos',
		currency_code: 'LAK',
		call_code: '+856',
		capital: 'Vientiane',
	},
	{
		country: 'Latvia',
		currency_code: 'LVL',
		call_code: '+371',
		capital: 'Riga',
	},
	{
		country: 'Lebanon',
		currency_code: 'LBP',
		call_code: '+961',
		capital: 'Beirut',
	},
	{
		country: 'Lesotho',
		currency_code: 'LSL',
		call_code: '+266',
		capital: 'Maseru',
	},
	{
		country: 'Liberia',
		currency_code: 'LRD',
		call_code: '+231',
		capital: 'Monrovia',
	},
	{
		country: 'Libyan Arab Jamahiriya',
		currency_code: 'LYD',
		call_code: '+218',
		capital: 'Tripoli',
	},
	{
		country: 'Liechtenstein',
		currency_code: 'CHF',
		call_code: '+423',
		capital: 'Vaduz',
	},
	{
		country: 'Lithuania',
		currency_code: 'LTL',
		call_code: '+370',
		capital: 'Vilnius',
	},
	{
		country: 'Luxembourg',
		currency_code: 'EUR',
		call_code: '+352',
		capital: 'Luxembourg',
	},
	{
		country: 'Macao',
		currency_code: 'MOP',
		call_code: '+853',
		capital: 'Macao',
	},
	{
		country: 'North Macedonia',
		currency_code: 'MKD',
		call_code: '+389',
		capital: 'Skopje',
	},
	{
		country: 'Madagascar',
		currency_code: 'MGF',
		call_code: '+261',
		capital: 'Antananarivo',
	},
	{
		country: 'Malawi',
		currency_code: 'MWK',
		call_code: '+265',
		capital: 'Lilongwe',
	},
	{
		country: 'Malaysia',
		currency_code: 'MYR',
		call_code: '+60',
		capital: 'Kuala Lumpur',
	},
	{
		country: 'Maldives',
		currency_code: 'MVR',
		call_code: '+960',
		capital: 'Malé',
	},
	{
		country: 'Mali',
		currency_code: 'XOF',
		call_code: '+223',
		capital: 'Bamako',
	},
	{
		country: 'Malta',
		currency_code: 'EUR',
		call_code: '+356',
		capital: 'Valletta',
	},
	{
		country: 'Marshall Islands',
		currency_code: 'USD',
		call_code: '+692',
		capital: 'Majuro',
	},
	{
		country: 'Martinique',
		currency_code: 'EUR',
		call_code: '+596',
		capital: 'Fort-de-France',
	},
	{
		country: 'Mauritania',
		currency_code: 'MRO',
		call_code: '+222',
		capital: 'Nouakchott',
	},
	{
		country: 'Mauritius',
		currency_code: 'MUR',
		call_code: '+230',
		capital: 'Port Louis',
	},
	{
		country: 'Mayotte',
		currency_code: 'EUR',
		call_code: '+262',
		capital: 'Mamoudzou',
	},
	{
		country: 'Mexico',
		currency_code: 'MXN',
		call_code: '+52',
		capital: 'Mexico City',
	},
	{
		country: 'Micronesia, Federated States of',
		currency_code: 'USD',
		call_code: '+691',
		capital: 'Palikir',
	},
	{
		country: 'Moldova',
		currency_code: 'MDL',
		call_code: '+373',
		capital: 'Chisinau',
	},
	{
		country: 'Monaco',
		currency_code: 'EUR',
		call_code: '+377',
		capital: 'Monaco',
	},
	{
		country: 'Mongolia',
		currency_code: 'MNT',
		call_code: '+976',
		capital: 'Ulan Bator',
	},
	{
		country: 'Montserrat',
		currency_code: 'XCD',
		call_code: '+1664',
		capital: 'Plymouth',
	},
	{
		country: 'Morocco',
		currency_code: 'MAD',
		call_code: '+212',
		capital: 'Rabat',
	},
	{
		country: 'Mozambique',
		currency_code: 'MZN',
		call_code: '+258',
		capital: 'Maputo',
	},
	{
		country: 'Myanmar',
		currency_code: 'MMR',
		call_code: '+95',
		capital: 'Naypyidaw',
	},
	{
		country: 'Namibia',
		currency_code: 'NAD',
		call_code: '+264',
		capital: 'Windhoek',
	},
	{
		country: 'Nauru',
		currency_code: 'AUD',
		call_code: '+674',
		capital: 'Yaren',
	},
	{
		country: 'Nepal',
		currency_code: 'NPR',
		call_code: '+977',
		capital: 'Kathmandu',
	},
	{
		country: 'Netherlands',
		currency_code: 'EUR',
		call_code: '+31',
		capital: 'Amsterdam',
	},
	{
		country: 'Netherlands Antilles',
		currency_code: 'ANG',
		call_code: '+599',
		capital: 'Willemstad',
	},
	{
		country: 'New Caledonia',
		currency_code: 'XPF',
		call_code: '+687',
		capital: 'Noumea',
	},
	{
		country: 'New Zealand',
		currency_code: 'NZD',
		call_code: '+64',
		capital: 'Wellington',
	},
	{
		country: 'Nicaragua',
		currency_code: 'NIO',
		call_code: '+505',
		capital: 'Managua',
	},
	{
		country: 'Niger',
		currency_code: 'XOF',
		call_code: '+227',
		capital: 'Niamey',
	},
	{
		country: 'Nigeria',
		currency_code: 'NGN',
		call_code: '+234',
		capital: 'Abuja',
	},
	{
		country: 'Niue',
		currency_code: 'NZD',
		call_code: '+683',
		capital: 'Alofi',
	},
	{
		country: 'Norfolk Island',
		currency_code: 'AUD',
		call_code: '+672',
		capital: 'Kingston',
	},
	{
		country: 'North Korea',
		currency_code: 'KPW',
		call_code: '+850',
		capital: 'Pyongyang',
	},
	{
		country: 'Northern Ireland',
		currency_code: 'GBP',
		call_code: '+44',
		capital: 'Belfast',
	},
	{
		country: 'Northern Mariana Islands',
		currency_code: 'USD',
		call_code: '+1670',
		capital: 'Saipan',
	},
	{
		country: 'Norway',
		currency_code: 'NOK',
		call_code: '+47',
		capital: 'Oslo',
	},
	{
		country: 'Oman',
		currency_code: 'OMR',
		call_code: '+968',
		capital: 'Muscat',
	},
	{
		country: 'Pakistan',
		currency_code: 'PKR',
		call_code: '+92',
		capital: 'Islamabad',
	},
	{
		country: 'Palau',
		currency_code: 'USD',
		call_code: '+680',
		capital: 'Ngerulmud',
	},
	{
		country: 'Palestine',
		currency_code: 'ILS',
		call_code: '+970',
		capital: 'State of Palestine',
	},
	{
		country: 'Panama',
		currency_code: 'PAB',
		call_code: '+507',
		capital: 'Panama City',
	},
	{
		country: 'Papua New Guinea',
		currency_code: 'PGK',
		call_code: '+675',
		capital: 'Port Moresby',
	},
	{
		country: 'Paraguay',
		currency_code: 'PYG',
		call_code: '+595',
		capital: 'Asuncion',
	},
	{
		country: 'Peru',
		currency_code: 'PEN',
		call_code: '+51',
		capital: 'Lima',
	},
	{
		country: 'Philippines',
		currency_code: 'PHP',
		call_code: '+63',
		capital: 'Manila',
	},
	{
		country: 'Pitcairn',
		currency_code: 'NZD',
		call_code: '+64',
		capital: 'Adamstown',
	},
	{
		country: 'Poland',
		currency_code: 'PLN',
		call_code: '+48',
		capital: 'Warsaw',
	},
	{
		country: 'Portugal',
		currency_code: 'EUR',
		call_code: '+351',
		capital: 'Lisbon',
	},
	{
		country: 'Puerto Rico',
		currency_code: 'USD',
		call_code: '+1',
		capital: 'San Juan',
	},
	{
		country: 'Qatar',
		currency_code: 'QAR',
		call_code: '+974',
		capital: 'Doha',
	},
	{
		country: 'Reunion',
		currency_code: 'EUR',
		call_code: '+262',
		capital: 'Saint-Denis',
	},
	{
		country: 'Romania',
		currency_code: 'RON',
		call_code: '+40',
		capital: 'Bucharest',
	},
	{
		country: 'Russian Federation',
		currency_code: 'RUB',
		call_code: '+7',
		capital: 'Moscow',
	},
	{
		country: 'Rwanda',
		currency_code: 'RWF',
		call_code: '+250',
		capital: 'Kigali',
	},
	{
		country: 'Saint Helena',
		currency_code: 'SHP',
		call_code: '+290',
		capital: 'Jamestown',
	},
	{
		country: 'Saint Kitts and Nevis',
		currency_code: 'XCD',
		call_code: '+1',
		capital: 'Basseterre',
	},
	{
		country: 'Saint Lucia',
		currency_code: 'XCD',
		call_code: '+1',
		capital: 'Castries',
	},
	{
		country: 'Saint Pierre and Miquelon',
		currency_code: 'EUR',
		call_code: '+508',
		capital: 'Saint-Pierre',
	},
	{
		country: 'Saint Vincent and the Grenadines',
		currency_code: 'XCD',
		call_code: '+1',
		capital: 'Kingstown',
	},
	{
		country: 'Samoa',
		currency_code: 'WST',
		call_code: '+685',
		capital: 'Apia',
	},
	{
		country: 'San Marino',
		currency_code: 'EUR',
		call_code: '+378',
		capital: 'San Marino',
	},
	{
		country: 'Sao Tome and Principe',
		currency_code: 'STD',
		call_code: '+239',
		capital: 'Sao Tome',
	},
	{
		country: 'Saudi Arabia',
		currency_code: 'SAR',
		call_code: '+966',
		capital: 'Riyadh',
	},
	{
		country: 'Scotland',
		currency_code: 'GBP',
		call_code: '+44',
		capital: 'Edinburgh',
	},
	{
		country: 'Senegal',
		currency_code: 'XOF',
		call_code: '+221',
		capital: 'Dakar',
	},
	{
		country: 'Seychelles',
		currency_code: 'SCR',
		call_code: '+248',
		capital: 'Victoria',
	},
	{
		country: 'Sierra Leone',
		currency_code: 'SLL',
		call_code: '+232',
		capital: 'Freetown',
	},
	{
		country: 'Singapore',
		currency_code: 'SGD',
		call_code: '+65',
		capital: 'Singapore',
	},
	{
		country: 'Slovakia',
		currency_code: 'EUR',
		call_code: '+421',
		capital: 'Bratislava',
	},
	{
		country: 'Slovenia',
		currency_code: 'EUR',
		call_code: '+386',
		capital: 'Ljubljana',
	},
	{
		country: 'Solomon Islands',
		currency_code: 'SBD',
		call_code: '+677',
		capital: 'Honiara',
	},
	{
		country: 'Somalia',
		currency_code: 'SOS',
		call_code: '+252',
		capital: 'Mogadishu',
	},
	{
		country: 'South Africa',
		currency_code: 'ZAR',
		call_code: '+27',
		capital: 'Pretoria',
	},
	{
		country: 'South Georgia and the South Sandwich Islands',
		currency_code: 'GBP',
		call_code: '+44',
		capital: 'Grytviken',
	},
	{
		country: 'South Korea',
		currency_code: 'KRW',
		call_code: '+82',
		capital: 'Seoul',
	},
	{
		country: 'South Sudan',
		currency_code: 'SSP',
		call_code: '+211',
		capital: 'Juba',
	},
	{
		country: 'Spain',
		currency_code: 'EUR',
		call_code: '+34',
		capital: 'Madrid',
	},
	{
		country: 'SriLanka',
		currency_code: 'LKR',
		call_code: '+94',
		capital: 'Colombo',
	},
	{
		country: 'Sudan',
		currency_code: 'SDG',
		call_code: '+249',
		capital: 'Khartoum',
	},
	{
		country: 'Suriname',
		currency_code: 'SRD',
		call_code: '+597',
		capital: 'Paramaribo',
	},
	{
		country: 'Svalbard and Jan Mayen',
		currency_code: 'NOK',
		call_code: '+47',
		capital: 'Longyearbyen',
	},
	{
		country: 'Swaziland',
		currency_code: 'SZL',
		call_code: '+268',
		capital: 'Mbabane',
	},
	{
		country: 'Sweden',
		currency_code: 'SEK',
		call_code: '+46',
		capital: 'Stockholm',
	},
	{
		country: 'Switzerland',
		currency_code: 'CHF',
		call_code: '+41',
		capital: 'Berne',
	},
	{
		country: 'Syria',
		currency_code: 'SYP',
		call_code: '+963',
		capital: 'Damascus',
	},
	{
		country: 'Tajikistan',
		currency_code: 'TJS',
		call_code: '+992',
		capital: 'Dushanbe',
	},
	{
		country: 'Tanzania',
		currency_code: 'TZS',
		call_code: '+255',
		capital: 'Dodoma',
	},
	{
		country: 'Thailand',
		currency_code: 'THB',
		call_code: '+66',
		capital: 'Bangkok',
	},
	{
		country: 'The Democratic Republic of Congo',
		currency_code: 'CDF',
		call_code: '+243',
		capital: 'Kinshasa',
	},
	{
		country: 'Togo',
		currency_code: 'XOF',
		call_code: '+228',
		capital: 'Lomé',
	},
	{
		country: 'Tokelau',
		currency_code: 'NZD',
		call_code: '+690',
		capital: '',
	},
	{
		country: 'Tonga',
		currency_code: 'TOP',
		call_code: '+676',
		capital: 'Nukuʻalofa',
	},
	{
		country: 'Trinidad and Tobago',
		currency_code: 'TTD',
		call_code: '+1',
		capital: 'Port of Spain',
	},
	{
		country: 'Tunisia',
		currency_code: 'TND',
		call_code: '+216',
		capital: 'Tunis',
	},
	{
		country: 'Turkey',
		currency_code: 'TRY',
		call_code: '+90',
		capital: 'Ankara',
	},
	{
		country: 'Turkmenistan',
		currency_code: 'TMT',
		call_code: '+993'
	},
	{
		country: 'Turks and Caicos Islands',
		currency_code: 'USD',
		call_code: '+1',
		capital: 'Cockburn Town',
	},
	{
		country: 'Tuvalu',
		currency_code: 'AUD',
		call_code: '+688',
		capital: 'Funafuti',
	},
	{
		country: 'Uganda',
		currency_code: 'UGX',
		call_code: '+256',
		capital: 'Kampala',
	},
	{
		country: 'Ukraine',
		currency_code: 'UAH',
		call_code: '+380',
		capital: 'Kiev',
	},
	{
		country: 'United Arab Emirates',
		currency_code: 'AED',
		call_code: '+971',
		capital: 'Abu Dhabi',
	},
	{
		country: 'United Kingdom',
		currency_code: 'GBP',
		call_code: '+44',
		capital: 'London',
	},
	{
		country: 'United States',
		currency_code: 'USD',
		call_code: '+1',
		capital: 'Washington D.C.',
	},
	{
		country: 'United States Minor Outlying Islands',
		currency_code: 'USD',
		call_code: '+1',
		capital: '',
	},
	{
		country: 'Uruguay',
		currency_code: 'UYU',
		call_code: '+598',
		capital: 'Montevideo',
	},
	{
		country: 'Uzbekistan',
		currency_code: 'UZS',
		call_code: '+998',
		capital: 'Tashkent',
	},
	{
		country: 'Vanuatu',
		currency_code: 'VUV',
		call_code: '+678',
		capital: 'Port Vila',
	},
	{
		country: 'Venezuela',
		currency_code: 'VEF',
		call_code: '+58',
		capital: 'Caracas',
	},
	{
		country: 'Vietnam',
		currency_code: 'VND',
		call_code: '+84',
		capital: 'Hanoi',
	},
	{
		country: 'Virgin Islands, British',
		currency_code: 'USD',
		call_code: '+1',
		capital: 'Road Town',
	},
	{
		country: 'Virgin Islands, U.S.',
		currency_code: 'USD',
		call_code: '+1',
		capital: 'Charlotte Amalie',
	},
	{
		country: 'Wales',
		currency_code: 'GBP',
		call_code: '+44',
		capital: 'Cardiff',
	},
	{
		country: 'Wallis and Futuna',
		currency_code: 'XPF',
		call_code: '+681',
		capital: 'Mata-Utu',
	},
	{
		country: 'Western Sahara',
		currency_code: 'MAD',
		call_code: '+212',
		capital: 'El Aaiún',
	},
	{
		country: 'Yemen',
		currency_code: 'YER',
		call_code: '+967',
		capital: 'Sanaá',
	},
	{
		country: 'Yugoslavia',
		currency_code: 'YUM',
		call_code: '+38',
		capital: 'Belgrade',
	},
	{
		country: 'Zambia',
		currency_code: 'ZMW',
		call_code: '+260',
		capital: 'Lusaka',

	},
	{
		country: 'Zimbabwe',
		currency_code: 'ZWD',
		call_code: '+263',
		capital: 'Harare',
	},
];